"""make migration

Revision ID: bb5fb4c81bcc
Revises: 587010e524d5
Create Date: 2025-10-22 08:41:51.160959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5fb4c81bcc'
down_revision: Union[str, Sequence[str], None] = '587010e524d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=True)
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
